apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classification-deployment
  labels:
    app: image-classification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classification-app
  template:
    metadata:
      labels:
        app: image-classification-app
    spec:
      containers:
      - name: image-classification
        image: ali19y19/imageclassification:0.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
      - name: exporter
        image: ali19y19/exporter:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-metric
          containerPort: 9877
      nodeSelector:
        node-role.kubernetes.io/worker: worker