apiVersion: v1
kind: Service
metadata:  
  name: image-classification-sercice
spec:
  selector:    
    app: image-classification-app
  type: NodePort
  ports:  
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30036
    protocol: TCP