apiVersion: v1
kind: Service
metadata:  
  name: image-classification-sercice
spec:
  selector:    
    app: image-classification-app
  type: NodePort
  ports:  
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30036
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: image-classification-monitoring-service
  labels:
    - app: image-classification-monitoring
spec:
  selector:
    app: image-classification-app
  type: ClusterIP
  ports:
    - name: http-metric
      port: 9877
      targetPort: http-metric